# -*- coding: utf-8 -*-
"""notebook_SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K3lBVSpOgXRAVFastHDEzxWmaKvgBqQT
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv('diabetes.csv')
df.head()

df.info()

# separate the attributes in the dataset and stores them in a variable
X = df[df.columns[:8]]

# separate the labels in the dataset and stores them in a variable
y = df['Outcome']

from sklearn.preprocessing import StandardScaler

# standardize the values of the dataset
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

from sklearn.model_selection import train_test_split

# split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

from sklearn.svm import SVC

# create an SVC object and train the model
clf = SVC()
clf.fit(X_train, y_train)

# calculate the accuracy score of the data train
clf.score(X_train, y_train)

# calculate the accuracy score of prediction
clf.score(X_test, y_test)